language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10
    - node_js: 8 # temporarly, since npm does not cooperate
notifications:
  email: false
script:
  - npm test

